white-list-external: ["localhost"]
external-links-to-ignore: ["localhost"]
black-list: ["node_modules"]
files-to-ignore: ["node_modules"]
timeout: 60
request-repeats: 5
files:
  - path: "./documentation-component/.github/ISSUE_TEMPLATE/security-vulnerability.md"
    config:
      white-list-internal: ["{CVSS"]
      internal-links-to-ignore: ["{CVSS"]
      white-list-external:
        [
          "https://www.first.org/cvss/calculator/3.0#CVSS:3.0/AV:N/AC:L/PR:L/UI:N/S:U/C:H/I:L/A:N",
        ]
      external-links-to-ignore:
        [
          "https://www.first.org/cvss/calculator/3.0#CVSS:3.0/AV:N/AC:L/PR:L/UI:N/S:U/C:H/I:L/A:N",
        ]
